import './App.css'
import { useState } from 'react'
import { Routes, Route } from 'react-router-dom'
import { Navbar } from './components/Navbar'
import { HomePage } from './pages/HomePage'
import { BrowsePage } from './pages/BrowsePage'
import { ItemDetailsPage } from './pages/ItemDetailsPage'
import { LoginPage } from './pages/LoginPage'
import { SignUpPage } from './pages/SignUpPage'
import { StaffReportPage } from './pages/StaffReportPage'
import { StaffDashboardPage } from './pages/StaffDashboardPage'
import { StaffItemsPage } from './pages/StaffItemsPage'

export type UserRole = 'public' | 'staff' | 'superadmin';

export interface Finder {
  name: string;
  contact: string;
  affiliation?: string | null;
}

export interface Item {
  id: number;
  name: string;
  description: string;
  color: string;
  color_hex: string;
  color_bucket: string;
  category: string;
  location: string;
  found_location: string;
  found_at: string;
  building: string;
  foundAt: string; // for display
  expiry: string;
  status: string;
  image: string;
  notes?: string;
  finder: Finder;
  photos: string[];
}

function App() {
  const [isSignedIn, setIsSignedIn] = useState(false)
  const [userName, setUserName] = useState('')
  const [userRole, setUserRole] = useState<UserRole>('public')

  const items: Item[] = [
    {
      id: 1,
      name: 'Black laptop bag',
      description: 'A black leather laptop bag with multiple compartments and padded shoulder straps. Found with personal documents inside.',
      color: 'Black',
      color_hex: '#1a1a1a',
      color_bucket: 'Black',
      category: 'Electronics',
      location: 'Student Lounge',
      found_location: 'Student Lounge',
      found_at: '2026-04-21T14:30',
      building: 'FX Campus',
      foundAt: 'April 21, 2026',
      expiry: 'May 21, 2026',
      status: 'Active',
      image: '/placeholder.png',
      notes: 'A black leather laptop bag with multiple compartments and padded shoulder straps. Found with personal documents inside.',
      finder: { name: 'Alex Tan', contact: 'alex.tan@binus.ac.id', affiliation: 'Student' },
      photos: [],
    },
    {
      id: 2,
      name: 'Student ID card',
      description: 'Blue BINUS student ID card with photo. Name visible on card.',
      color: 'Blue',
      color_hex: '#2563eb',
      color_bucket: 'Blue',
      category: 'Personal Belonging',
      location: 'Auditorium',
      found_location: 'Auditorium',
      found_at: '2026-04-20T10:15',
      building: 'JWC Campus',
      foundAt: 'April 20, 2026',
      expiry: 'May 20, 2026',
      status: 'Active',
      image: '/placeholder.png',
      notes: 'Blue BINUS student ID card with photo. Name visible on card.',
      finder: { name: 'Maya Sari', contact: 'maya.sari@binus.ac.id', affiliation: 'Staff' },
      photos: [],
    },
    {
      id: 3,
      name: 'Blue water bottle',
      description: 'Stainless steel water bottle with blue exterior and white logo print. Lightly used.',
      color: 'Blue',
      color_hex: '#2563eb',
      color_bucket: 'Blue',
      category: 'Personal Belonging',
      location: 'Room 205',
      found_location: 'Room 205',
      found_at: '2026-04-19T09:45',
      building: 'FX Campus',
      foundAt: 'April 19, 2026',
      expiry: 'May 19, 2026',
      status: 'Active',
      image: '/placeholder.png',
      notes: 'Stainless steel water bottle with blue exterior and white logo print. Lightly used.',
      finder: { name: 'Rudi Hartono', contact: '0812-3456-7890', affiliation: 'Student' },
      photos: [],
    },
    {
      id: 4,
      name: 'Wireless earbuds',
      description: 'White wireless earbuds with charging case. Brand name visible on case.',
      color: 'White',
      color_hex: '#f5f5f5',
      color_bucket: 'White',
      category: 'Electronics',
      location: 'Library',
      found_location: 'Library',
      found_at: '2026-04-18T15:20',
      building: 'JWC Campus',
      foundAt: 'April 18, 2026',
      expiry: 'May 18, 2026',
      status: 'Active',
      image: '/placeholder.png',
      notes: 'White wireless earbuds with charging case. Brand name visible on case.',
      finder: { name: 'Eka Putri', contact: 'eka.putri@binus.ac.id', affiliation: 'Student' },
      photos: [],
    },
    {
      id: 5,
      name: 'Red backpack',
      description: 'Red canvas backpack with multiple pockets and adjustable straps.',
      color: 'Red',
      color_hex: '#ef4444',
      color_bucket: 'Red',
      category: 'Other',
      location: 'Lobby',
      found_location: 'Lobby',
      found_at: '2026-04-17T11:00',
      building: 'FX Campus',
      foundAt: 'April 17, 2026',
      expiry: 'May 17, 2026',
      status: 'Claimed',
      image: '/placeholder.png',
      notes: 'Red canvas backpack with multiple pockets and adjustable straps.',
      finder: { name: 'Budi Wijaya', contact: 'budi.wijaya@binus.ac.id', affiliation: 'Staff' },
      photos: [],
    },
    {
      id: 6,
      name: 'Gray jacket',
      description: 'Winter gray jacket size M. Has BINUS logo on sleeve.',
      color: 'Gray',
      color_hex: '#94a3b8',
      color_bucket: 'Gray',
      category: 'Clothing',
      location: 'Student Lounge',
      found_location: 'Student Lounge',
      found_at: '2026-04-16T13:30',
      building: 'JWC Campus',
      foundAt: 'April 16, 2026',
      expiry: 'May 16, 2026',
      status: 'Claimed',
      image: '/placeholder.png',
      notes: 'Winter gray jacket size M. Has BINUS logo on sleeve.',
      finder: { name: 'Hendra', contact: 'hendra@binus.ac.id', affiliation: 'Staff' },
      photos: [],
    },
    {
      id: 7,
      name: 'Green sports bag',
      description: 'Green duffel bag with sports equipment inside including tennis racket.',
      color: 'Green',
      color_hex: '#22c55e',
      color_bucket: 'Green',
      category: 'Sports Equipment',
      location: 'Room 612',
      found_location: 'Room 612',
      found_at: '2026-04-15T16:45',
      building: 'FX Campus',
      foundAt: 'April 15, 2026',
      expiry: 'May 15, 2026',
      status: 'Returned',
      image: '/placeholder.png',
      notes: 'Green duffel bag with sports equipment inside including tennis racket.',
      finder: { name: 'Dina Kusuma', contact: 'dina.kusuma@binus.ac.id', affiliation: 'Student' },
      photos: [],
    },
    {
      id: 8,
      name: 'Black glasses case',
      description: 'Hard black case for eyeglasses with cleaning cloth inside.',
      color: 'Black',
      color_hex: '#1a1a1a',
      color_bucket: 'Black',
      category: 'Personal Belonging',
      location: 'Photography Room',
      found_location: 'Photography Room',
      found_at: '2026-04-14T12:15',
      building: 'JWC Campus',
      foundAt: 'April 14, 2026',
      expiry: 'May 14, 2026',
      status: 'Claimed',
      image: '/placeholder.png',
      notes: 'Hard black case for eyeglasses with cleaning cloth inside.',
      finder: { name: 'Siti Nurhaliza', contact: '0811-2345-6789', affiliation: null },
      photos: [],
    },
    {
      id: 9,
      name: 'Blue phone charger',
      description: 'USB-C phone charger with blue cable. Looks relatively new.',
      color: 'Blue',
      color_hex: '#2563eb',
      color_bucket: 'Blue',
      category: 'Electronics',
      location: 'Library',
      found_location: 'Library',
      found_at: '2026-04-13T14:00',
      building: 'FX Campus',
      foundAt: 'April 13, 2026',
      expiry: 'May 13, 2026',
      status: 'Active',
      image: '/placeholder.png',
      notes: 'USB-C phone charger with blue cable. Looks relatively new.',
      finder: { name: 'Toni Saputra', contact: 'toni.saputra@binus.ac.id', affiliation: 'Student' },
      photos: [],
    },
    {
      id: 10,
      name: 'White sneakers',
      description: 'White canvas sneakers size 9. Good condition, only lightly worn.',
      color: 'White',
      color_hex: '#f5f5f5',
      color_bucket: 'White',
      category: 'Clothing',
      location: 'Room 102',
      found_location: 'Room 102',
      found_at: '2026-04-12T10:30',
      building: 'JWC Campus',
      foundAt: 'April 12, 2026',
      expiry: 'May 12, 2026',
      status: 'Returned',
      image: '/placeholder.png',
      notes: 'White canvas sneakers size 9. Good condition, only lightly worn.',
      finder: { name: 'Wina Widjaya', contact: 'wina.widjaya@binus.ac.id', affiliation: 'Staff' },
      photos: [],
    },
    {
      id: 11,
      name: 'Red notebook',
      description: 'Red hardcover notebook with lined pages. Contains lecture notes inside.',
      color: 'Red',
      color_hex: '#ef4444',
      color_bucket: 'Red',
      category: 'Personal Belonging',
      location: 'Meeting Room',
      found_location: 'Meeting Room',
      found_at: '2026-04-11T11:45',
      building: 'FX Campus',
      foundAt: 'April 11, 2026',
      expiry: 'May 11, 2026',
      status: 'Active',
      image: '/placeholder.png',
      notes: 'Red hardcover notebook with lined pages. Contains lecture notes inside.',
      finder: { name: 'Joni Santoso', contact: 'joni.santoso@binus.ac.id', affiliation: 'Staff' },
      photos: [],
    },
    {
      id: 12,
      name: 'Black tennis racket',
      description: 'Professional black tennis racket with strings intact. Excellent condition.',
      color: 'Black',
      color_hex: '#1a1a1a',
      color_bucket: 'Black',
      category: 'Sports Equipment',
      location: 'Room 620',
      found_location: 'Room 620',
      found_at: '2026-04-10T15:15',
      building: 'JWC Campus',
      foundAt: 'April 10, 2026',
      expiry: 'May 10, 2026',
      status: 'Returned',
      image: '/placeholder.png',
      notes: 'Professional black tennis racket with strings intact. Excellent condition.',
      finder: { name: 'Kurnia', contact: 'kurnia@binus.ac.id', affiliation: 'Student' },
      photos: [],
    },
    {
      id: 13,
      name: 'Gray laptop stand',
      description: 'Adjustable gray aluminum laptop stand for desk setup.',
      color: 'Gray',
      color_hex: '#94a3b8',
      color_bucket: 'Gray',
      category: 'Electronics',
      location: 'Library',
      found_location: 'Library',
      found_at: '2026-04-09T09:00',
      building: 'FX Campus',
      foundAt: 'April 9, 2026',
      expiry: 'May 9, 2026',
      status: 'Active',
      image: '/placeholder.png',
      notes: 'Adjustable gray aluminum laptop stand for desk setup.',
      finder: { name: 'Lina Santoso', contact: '0821-9876-5432', affiliation: 'Student' },
      photos: [],
    },
    {
      id: 14,
      name: 'Green umbrella',
      description: 'Compact green umbrella with auto-open feature.',
      color: 'Green',
      color_hex: '#22c55e',
      color_bucket: 'Green',
      category: 'Other',
      location: 'Sleeping Pods',
      found_location: 'Sleeping Pods',
      found_at: '2026-04-08T13:20',
      building: 'JWC Campus',
      foundAt: 'April 8, 2026',
      expiry: 'May 8, 2026',
      status: 'Active',
      image: '/placeholder.png',
      notes: 'Compact green umbrella with auto-open feature.',
      finder: { name: 'Mulia', contact: 'mulia@binus.ac.id', affiliation: 'Staff' },
      photos: [],
    },
    {
      id: 15,
      name: 'Blue headphones',
      description: 'Over-ear blue headphones with noise cancellation. Still has warranty sticker.',
      color: 'Blue',
      color_hex: '#2563eb',
      color_bucket: 'Blue',
      category: 'Electronics',
      location: 'Auditorium',
      found_location: 'Auditorium',
      found_at: '2026-04-07T16:30',
      building: 'FX Campus',
      foundAt: 'April 7, 2026',
      expiry: 'May 7, 2026',
      status: 'Active',
      image: '/placeholder.png',
      notes: 'Over-ear blue headphones with noise cancellation. Still has warranty sticker.',
      finder: { name: 'Nadia Rahman', contact: 'nadia.rahman@binus.ac.id', affiliation: 'Student' },
      photos: [],
    },
    {
      id: 16,
      name: 'Black wallet',
      description: 'Leather bifold wallet with multiple card slots. Contains student discount card.',
      color: 'Black',
      color_hex: '#1a1a1a',
      color_bucket: 'Black',
      category: 'Personal Belonging',
      location: 'Student Lounge',
      found_location: 'Student Lounge',
      found_at: '2026-04-06T10:45',
      building: 'JWC Campus',
      foundAt: 'April 6, 2026',
      expiry: 'May 6, 2026',
      status: 'Active',
      image: '/placeholder.png',
      notes: 'Leather bifold wallet with multiple card slots. Contains student discount card.',
      finder: { name: 'Okta Wijaya', contact: 'okta.wijaya@binus.ac.id', affiliation: 'Staff' },
      photos: [],
    },
    {
      id: 17,
      name: 'Red sports shoe',
      description: 'Red athletic shoe size 10 with white trim. Nike brand.',
      color: 'Red',
      color_hex: '#ef4444',
      color_bucket: 'Red',
      category: 'Clothing',
      location: 'Room 312',
      found_location: 'Room 312',
      found_at: '2026-04-05T12:00',
      building: 'FX Campus',
      foundAt: 'April 5, 2026',
      expiry: 'May 5, 2026',
      status: 'Active',
      image: '/placeholder.png',
      notes: 'Red athletic shoe size 10 with white trim. Nike brand.',
      finder: { name: 'Peri Suryanto', contact: 'peri.suryanto@binus.ac.id', affiliation: 'Student' },
      photos: [],
    },
    {
      id: 18,
      name: 'White phone case',
      description: 'Protective white phone case for iPhone 15. Barely used.',
      color: 'White',
      color_hex: '#f5f5f5',
      color_bucket: 'White',
      category: 'Electronics',
      location: 'Library',
      found_location: 'Library',
      found_at: '2026-04-04T14:15',
      building: 'JWC Campus',
      foundAt: 'April 4, 2026',
      expiry: 'May 4, 2026',
      status: 'Active',
      image: '/placeholder.png',
      notes: 'Protective white phone case for iPhone 15. Barely used.',
      finder: { name: 'Quentin Lee', contact: 'quentin.lee@binus.ac.id', affiliation: 'Student' },
      photos: [],
    },
    {
      id: 19,
      name: 'Gray scarf',
      description: 'Wool gray scarf approximately 2 meters long. Soft material.',
      color: 'Gray',
      color_hex: '#94a3b8',
      color_bucket: 'Gray',
      category: 'Clothing',
      location: 'Lobby',
      found_location: 'Lobby',
      found_at: '2026-04-03T11:30',
      building: 'FX Campus',
      foundAt: 'April 3, 2026',
      expiry: 'May 3, 2026',
      status: 'Active',
      image: '/placeholder.png',
      notes: 'Wool gray scarf approximately 2 meters long. Soft material.',
      finder: { name: 'Rita Hermawan', contact: 'rita.hermawan@binus.ac.id', affiliation: 'Staff' },
      photos: [],
    },
    {
      id: 20,
      name: 'Green water bottle',
      description: 'Eco-friendly green water bottle made from recycled plastic.',
      color: 'Green',
      color_hex: '#22c55e',
      color_bucket: 'Green',
      category: 'Personal Belonging',
      location: 'Room 205',
      found_location: 'Room 205',
      found_at: '2026-04-02T09:45',
      building: 'JWC Campus',
      foundAt: 'April 2, 2026',
      expiry: 'May 2, 2026',
      status: 'Active',
      image: '/placeholder.png',
      notes: 'Eco-friendly green water bottle made from recycled plastic.',
      finder: { name: 'Sandro', contact: 'sandro@binus.ac.id', affiliation: 'Student' },
      photos: [],
    },
    {
      id: 21,
      name: 'Blue jacket',
      description: 'Light blue windbreaker jacket. Size M. Very clean condition.',
      color: 'Blue',
      color_hex: '#2563eb',
      color_bucket: 'Blue',
      category: 'Clothing',
      location: 'Photography Room',
      found_location: 'Photography Room',
      found_at: '2026-04-01T15:00',
      building: 'FX Campus',
      foundAt: 'April 1, 2026',
      expiry: 'May 1, 2026',
      status: 'Active',
      image: '/placeholder.png',
      notes: 'Light blue windbreaker jacket. Size M. Very clean condition.',
      finder: { name: 'Tara Wilson', contact: 'tara.wilson@binus.ac.id', affiliation: 'Staff' },
      photos: [],
    },
    {
      id: 22,
      name: 'Black pen set',
      description: 'Set of 5 black ballpoint pens in original packaging.',
      color: 'Black',
      color_hex: '#1a1a1a',
      color_bucket: 'Black',
      category: 'Personal Belonging',
      location: 'Room 108',
      found_location: 'Room 108',
      found_at: '2026-03-31T10:20',
      building: 'JWC Campus',
      foundAt: 'March 31, 2026',
      expiry: 'April 30, 2026',
      status: 'Active',
      image: '/placeholder.png',
      notes: 'Set of 5 black ballpoint pens in original packaging.',
      finder: { name: 'Upik Novita', contact: 'upik.novita@binus.ac.id', affiliation: 'Student' },
      photos: [],
    },
    {
      id: 23,
      name: 'Red sports cap',
      description: 'Red baseball cap with embroidered BINUS logo.',
      color: 'Red',
      color_hex: '#ef4444',
      color_bucket: 'Red',
      category: 'Clothing',
      location: 'Auditorium',
      found_location: 'Auditorium',
      found_at: '2026-03-30T13:45',
      building: 'FX Campus',
      foundAt: 'March 30, 2026',
      expiry: 'April 29, 2026',
      status: 'Active',
      image: '/placeholder.png',
      notes: 'Red baseball cap with embroidered BINUS logo.',
      finder: { name: 'Vera', contact: 'vera@binus.ac.id', affiliation: 'Staff' },
      photos: [],
    },
    {
      id: 24,
      name: 'Gray backpack',
      description: 'Gray canvas backpack with laptop compartment and USB charging port.',
      color: 'Gray',
      color_hex: '#94a3b8',
      color_bucket: 'Gray',
      category: 'Other',
      location: 'Student Lounge',
      found_location: 'Student Lounge',
      found_at: '2026-03-29T11:15',
      building: 'JWC Campus',
      foundAt: 'March 29, 2026',
      expiry: 'April 28, 2026',
      status: 'Active',
      image: '/placeholder.png',
      notes: 'Gray canvas backpack with laptop compartment and USB charging port.',
      finder: { name: 'Wawan', contact: 'wawan@binus.ac.id', affiliation: 'Staff' },
      photos: [],
    },
    {
      id: 25,
      name: 'Green notebook',
      description: 'Green spiral-bound notebook, half-filled with notes.',
      color: 'Green',
      color_hex: '#22c55e',
      color_bucket: 'Green',
      category: 'Personal Belonging',
      location: 'Room 620',
      found_location: 'Room 620',
      found_at: '2026-03-28T14:30',
      building: 'FX Campus',
      foundAt: 'March 28, 2026',
      expiry: 'April 27, 2026',
      status: 'Active',
      image: '/placeholder.png',
      notes: 'Green spiral-bound notebook, half-filled with notes.',
      finder: { name: 'Xander', contact: 'xander@binus.ac.id', affiliation: 'Student' },
      photos: [],
    },
    {
      id: 26,
      name: 'White earbuds case',
      description: 'White protective case for wireless earbuds, empty.',
      color: 'White',
      color_hex: '#f5f5f5',
      color_bucket: 'White',
      category: 'Electronics',
      location: 'Library',
      found_location: 'Library',
      found_at: '2026-03-27T16:00',
      building: 'JWC Campus',
      foundAt: 'March 27, 2026',
      expiry: 'April 26, 2026',
      status: 'Active',
      image: '/placeholder.png',
      notes: 'White protective case for wireless earbuds, empty.',
      finder: { name: 'Yani', contact: 'yani@binus.ac.id', affiliation: 'Staff' },
      photos: [],
    },
    {
      id: 27,
      name: 'Blue water bottle (2)',
      description: 'Another blue water bottle, similar style. Capacity 1 liter.',
      color: 'Blue',
      color_hex: '#2563eb',
      color_bucket: 'Blue',
      category: 'Personal Belonging',
      location: 'Room 305',
      found_location: 'Room 305',
      found_at: '2026-03-26T12:45',
      building: 'FX Campus',
      foundAt: 'March 26, 2026',
      expiry: 'April 25, 2026',
      status: 'Active',
      image: '/placeholder.png',
      notes: 'Another blue water bottle, similar style. Capacity 1 liter.',
      finder: { name: 'Zia', contact: 'zia@binus.ac.id', affiliation: 'Student' },
      photos: [],
    },
    {
      id: 28,
      name: 'Black sneakers',
      description: 'Black canvas sneakers size 8. Adidas brand.',
      color: 'Black',
      color_hex: '#1a1a1a',
      color_bucket: 'Black',
      category: 'Clothing',
      location: 'Meeting Room',
      found_location: 'Meeting Room',
      found_at: '2026-03-25T10:15',
      building: 'JWC Campus',
      foundAt: 'March 25, 2026',
      expiry: 'April 24, 2026',
      status: 'Active',
      image: '/placeholder.png',
      notes: 'Black canvas sneakers size 8. Adidas brand.',
      finder: { name: 'Aldo', contact: 'aldo@binus.ac.id', affiliation: 'Staff' },
      photos: [],
    },
    {
      id: 29,
      name: 'Red mouse',
      description: 'Wireless red mouse with USB receiver. Good battery condition.',
      color: 'Red',
      color_hex: '#ef4444',
      color_bucket: 'Red',
      category: 'Electronics',
      location: 'Room 612',
      found_location: 'Room 612',
      found_at: '2026-03-24T13:30',
      building: 'FX Campus',
      foundAt: 'March 24, 2026',
      expiry: 'April 23, 2026',
      status: 'Active',
      image: '/placeholder.png',
      notes: 'Wireless red mouse with USB receiver. Good battery condition.',
      finder: { name: 'Bambang', contact: 'bambang@binus.ac.id', affiliation: 'Student' },
      photos: [],
    },
    {
      id: 30,
      name: 'Gray pen holder',
      description: 'Desk organizer with gray color. Multiple compartments for pens and supplies.',
      color: 'Gray',
      color_hex: '#94a3b8',
      color_bucket: 'Gray',
      category: 'Other',
      location: 'Sleeping Pods',
      found_location: 'Sleeping Pods',
      found_at: '2026-03-23T15:45',
      building: 'JWC Campus',
      foundAt: 'March 23, 2026',
      expiry: 'April 22, 2026',
      status: 'Active',
      image: '/placeholder.png',
      notes: 'Desk organizer with gray color. Multiple compartments for pens and supplies.',
      finder: { name: 'Cecilia', contact: 'cecilia@binus.ac.id', affiliation: 'Staff' },
      photos: [],
    },
  ]

  const handleLogout = () => {
    setIsSignedIn(false)
    setUserName('')
    setUserRole('public')
  }

  const handleLoginSuccess = (name: string, role: UserRole = 'public') => {
    setUserName(name)
    setUserRole(role)
    setIsSignedIn(true)
  }

  return (
    <>
      <Navbar isSignedIn={isSignedIn} userName={userName} userRole={userRole} onLogout={handleLogout} />
      <Routes>
        <Route path="/" element={<HomePage items={items} />} />
        <Route path="/browse" element={<BrowsePage items={items} />} />
        <Route path="/items/:id" element={<ItemDetailsPage items={items} isSignedIn={isSignedIn} />} />
        <Route path="/login" element={<LoginPage onLoginSuccess={handleLoginSuccess} />} />
        <Route path="/signup" element={<SignUpPage onSignUpSuccess={(name) => handleLoginSuccess(name, 'public')} />} />
        <Route path="/staff" element={<StaffDashboardPage items={items} userName={userName} />} />
        <Route path="/staff/items" element={<StaffItemsPage items={items} />} />
        <Route path="/staff/report" element={<StaffReportPage />} />
      </Routes>
    </>
  )
}

export default App
